#!/usr/bin/env python3
"""
Generate hook-registry.json from the graph's chain hook pools (`chunking_plan.chains[].hooks`)
for the platform's teacher-only chain view (D50 ask 3; B-124, contract agreed in C-97).

The graph is the only edit surface. The body lists each chain that has a pool, keyed by
chain_id, its hooks in authored pool order (opener first; never re-sorted), each skill in
connects_to carried with its graph label. The header's revision is the sha256 of the
canonical JSON body (header excluded), the rule fact-scope-registry.json already uses.

It is also a gate. It fails, and writes nothing, on: a hook without id, connects_to, prompt
or note; an id used twice; an id in hook-ids-retired.txt (ids are never reused); a
connects_to skill that isn't a skill of the hook's own chain; or markup in a prompt or note.
Hooks are plain text, rendered literally ("$4" stays "$4"), so `[[`, backticks and `**`
are refused.

Usage:
    python3 scripts/generate_hook_registry.py curriculum-graph.json [--retired hook-ids-retired.txt] [--out hook-registry.json]
"""
import argparse
import hashlib
import json
import re
import sys

FIELDS = ("id", "connects_to", "prompt", "note")
MARKUP_RE = re.compile(r"\[\[|`|\*\*")
ID_RE = re.compile(r"^hook\.[a-z0-9]+(-[a-z0-9]+)*\.[a-z0-9]+(-[a-z0-9]+)*$")


def fail(errors):
    for e in errors:
        print(f"hook registry FAIL: {e}", file=sys.stderr)
    sys.exit(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("graph")
    ap.add_argument("--retired", default="hook-ids-retired.txt")
    ap.add_argument("--out", default="hook-registry.json")
    args = ap.parse_args()

    g = json.load(open(args.graph, encoding="utf-8"))
    label = {s["id"]: s["label"] for s in g["skills"]}
    retired = set()
    for line in open(args.retired, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if line:
            retired.add(line)
    if not retired:
        fail([f"extracted zero ids from {args.retired} (vacuity guard)"])

    errors, seen, chains = [], set(), {}
    for c in g["chunking_plan"]["chains"]:
        pool = c.get("hooks") or []
        if not pool:
            continue
        out = []
        for h in pool:
            hid = h.get("id")
            missing = [f for f in FIELDS if not h.get(f)]
            if missing:
                errors.append(f"{c['chain_id']}: hook {hid!r} missing {', '.join(missing)}")
                continue
            if not ID_RE.match(hid):
                errors.append(f"{hid}: not a hook.<area>.<name> id")
            if hid in seen:
                errors.append(f"{hid}: used twice")
            seen.add(hid)
            if hid in retired:
                errors.append(f"{hid}: retired in {args.retired}; hook ids are never reused")
            for sid in h["connects_to"]:
                if sid not in c["skills"]:
                    errors.append(f"{hid}: connects_to {sid}, which isn't a skill of {c['chain_id']}")
            for f in ("prompt", "note"):
                if MARKUP_RE.search(h[f]):
                    errors.append(f"{hid}: markup in {f} (hooks are plain text)")
            out.append({
                "id": hid,
                "connects_to": [{"id": sid, "label": label.get(sid, "")} for sid in h["connects_to"]],
                "prompt": h["prompt"],
                "note": h["note"],
            })
        chains[c["chain_id"]] = out
    if not chains:
        errors.append("no chain has a hook pool (vacuity guard)")
    if errors:
        fail(errors)

    body = {"chains": chains}
    canonical = json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    revision = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    doc = {
        "header": {
            "generated_from": f"{args.graph} v{g.get('version')}",
            "revision": revision,
            "revision_rule": "sha256 of the canonical JSON body (sort_keys, no whitespace, UTF-8), header excluded",
            "note": "GENERATED by scripts/generate_hook_registry.py. Do not hand-edit: edit the graph's chunking_plan.chains[].hooks and regenerate.",
        },
        "body": body,
    }
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    n = sum(len(v) for v in chains.values())
    print(f"{args.out}: {len(chains)} chains, {n} hooks, revision {revision[:12]}")


if __name__ == "__main__":
    main()
